-------CREATE A PROCEDURE TO DISPLAY EMP_NAME AND SALARY OF ALL THE EMPLOYEE.
create or replace procedure emp_details as
V_ENAME VARCHAR(25);
V_SAL NUMBER(25);
begin
select ename,sal INTO V_ENAME,V_SAL from emp;
DBMS_OUTPUT.PUT_LINE (V_ENAME || 'V_NAME');
DBMS_OUTPUT.PUT_LINE (V_SAL || 'V_SAL');
end;

BEGIN
  EMP_DETAILS();
--rollback; 
END;

DECLARE
S_EMPNO EMP.EMPNO%type;
S_Ename EMP.Ename%type;
S_SAL EMP.SAL%TYPE;
CURSOR CUR_EMP is
SELECT EMPNO, ENAME, SAL FROM EMP;
BEGIN
OPEN CUR_EMP;
LOOP
FETCH CUR_EMP into s_EMPNO, s_ENAME, S_SAL;
EXIT WHEN cur_EMP%notfound;
dbms_output.put_line(s_EMPNO || ' ' || s_ENAME || ' ' || S_SAL);
END LOOP;
CLOSE CUR_EMP;
END;

create or replace PROCEDURE EMPLOYEES_DETAILS ( V_EMPNO IN EMP.EMPNO%TYPE)
AS
V_ENAME EMPLOYEES.ENAME%TYPE;
V_SAL EMPLOYEES.SAL%TYPE;
BEGIN
SELECT ENAME, SAL INTO V_ENAME,V_SAL FROM EMP WHERE EMPNO = V_EMPNO;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE DETAILS !!!');
DBMS_OUTPUT.PUT_LINE ('ENAME = '|| V_ENAME);
DBMS_OUTPUT.PUT_LINE ('EMP_SAL = '|| V_SAL);
END;
create or replace procedure emp_details as
V_ENAME VARCHAR(25);
V_SAL NUMBER(25);
begin
select ename,sal INTO V_ENAME,V_SAL from emp;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE DETAILS !!!');
DBMS_OUTPUT.PUT_LINE ('ENAME = '|| V_ENAME);
DBMS_OUTPUT.PUT_LINE ('EMP_SAL = '|| V_SAL);
END;

create or replace procedure emp_details as
V_ENAME VARCHAR(25);
V_SAL NUMBER(25);
begin
select ename,sal INTO V_ENAME,V_SAL from emp;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE DETAILS !!!');
DBMS_OUTPUT.PUT_LINE ('ENAME = '|| V_ENAME);
DBMS_OUTPUT.PUT_LINE ('EMP_SAL = '|| V_SAL);
END;

create or replace procedure emp_details as
V_ENAME VARCHAR(25);
V_SAL NUMBER(25);
begin
select ename,sal INTO V_ENAME,V_SAL from emp;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE DETAILS !!!');
DBMS_OUTPUT.PUT_LINE ('ENAME = '|| V_ENAME);
DBMS_OUTPUT.PUT_LINE ('EMP_SAL = '|| V_SAL);
END;
------CREATE A PROCEDURE TO DISPLAY NAME, AGE AND SALARY OF ALL THE EMPLOYEE WHO BELONGS TO DEPT 10.

CREATE OR REPLACE PROCEDURE EMP_D AS
DECLARE
