DECLARE
  V_NAME VARCHAR2(20);
  V_MOBILE NUMBER;
  V_PROOF VARCHAR2(16);
  V_CITY VARCHAR2(20);
  V_AREA VARCHAR2(20);
  V_TYPE VARCHAR2(20);
  V_USERNAME VARCHAR2(10);
  V_PASSWORD VARCHAR2(20);
BEGIN
  V_NAME :='Anjuuu';
  V_MOBILE := 9875478556;
  V_PROOF := 'AADHAR';
  V_CITY := 'HYDERABAD';
  V_AREA := 'FALAKNUMA';
  V_TYPE := 'RETAIL';
  V_USERNAME := 'Mnju4';
  V_PASSWORD := 123087;

  REGISTER_USER(
    V_NAME => V_NAME,
    V_MOBILE => V_MOBILE,
    V_PROOF => V_PROOF,
    V_CITY => V_CITY,
    V_AREA => V_AREA,
    V_TYPE => V_TYPE,
    V_USERNAME => V_USERNAME,
    V_PASSWORD => V_PASSWORD
  );
--rollback; 
END;
