DECLARE
V_cust_id NUMBER(5);
V_cust_SALARY NUMBER(6);
V_INC_SAL NUMBER(6);
V_TOT_SAL NUMBER(6);
BEGIN
SELECT CUST_ID,CUST_SALARY,(CUST_SALARY * 0.10),(V_CUST_SALARY + V_INC_SAL) INTO V_CUST_ID, V_CUST_SALARY,V_INC_SAL,V_TOT_SAL
FROM CUSTOMERS WHERE CUST_ID = 1;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE NUMBER = ' ||V_CUST_ID);
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE SALARY = ' ||V_CUST_SALARY);
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE INC_SAL = ' ||V_INC_SAL);
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE TOTAL_SAL = ' ||V_TOT_SAL);
END;

SELECT * FROM ALL_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OWNER = 'SYS' AND TRUNC(CREATED) > '15-MAY-2022' ORDER BY OWNER;
drop table emp;
select * from customers;


SELECT * FROM EMP;
SELECT * FROM EMPloyee1;
desc emp;

SELECT * FROM DEPT;
DESC DEPT;