create or replace PROCEDURE EMP_DETAILS ( V_EMPNO IN EMP.EMPNO%TYPE)
AS
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
BEGIN
SELECT ENAME, SAL INTO V_ENAME,V_SAL FROM EMP WHERE EMPNO = V_EMPNO;
DBMS_OUTPUT.PUT_LINE ('EMPLOYEE DETAILS !!!');
DBMS_OUTPUT.PUT_LINE ('ENAME = '|| V_ENAME);
DBMS_OUTPUT.PUT_LINE ('EMP_SAL = '|| V_SAL);
END;
DECLARE
  V_EMPNO NUMBER;
BEGIN
  V_EMPNO := 7369;

  EMP_DETAILS(
    V_EMPNO => V_EMPNO
  );
--rollback; 
END;